# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votos', '0002_auto_20171124_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='votos',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
