# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_votos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votos',
            name='candidato',
            field=models.ForeignKey(default='Blanco', on_delete=django.db.models.deletion.CASCADE, to='votos.Candidato'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='votos',
            field=models.IntegerField(default=1),
        ),
    ]
